on:
  push:
    tags:
      - 'v*'

name: Create Release and Publish

jobs:
  release_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/app
        tag_with_ref: true
